export const castHourArrayItems = [
    {
      id: 1,
      title: '09:00 ~ 10:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 2,
      title: '10:00 ~ 11:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 3,
      title: '11:00 ~ 12:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 4,
      title: '12:00 ~ 13:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 5,
      title: '13:00 ~ 14:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 6,
      title: '14:00 ~ 15:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 7,
      title: '15:00 ~ 16:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 8,
      title: '16:00 ~ 17:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 9,
      title: '17:00 ~ 18:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 10,
      title: '18:00 ~ 19:00',
      active: false,
      isParent: false,
      blocked: false,
    },
    {
      id: 11,
      title: '19:00 ~ 20:00',
      active: false,
      isParent: false,
      blocked: false,
    },
  ]